$hostsFile = "C:\Windows\System32\drivers\etc\hosts"

Add-Content -Path $hostsFile -Value "192.168.132.1 expressvpnrouter.com"
Add-Content -Path $hostsFile -Value "192.168.133.218 www.expressvpnrouter.com"
Add-Content -Path $hostsFile -Value ""
Add-Content -Path $hostsFile -Value "# Added by Docker Desktop"
Add-Content -Path $hostsFile -Value "192.168.133.200 host.docker.internal"
Add-Content -Path $hostsFile -Value "192.168.133.200 gateway.docker.internal"
Add-Content -Path $hostsFile -Value "127.0.0.1 kubernetes.docker.internal"
Add-Content -Path $hostsFile -Value "# To allow the same kube context to work on the host and the container:"
Add-Content -Path $hostsFile -Value ""
